import subprocess

V = ['cust']
F = ['sum_1_quant', 'sum_2_quant', 'sum_3_quant']

def stringArrayToCommaString(stringArray):
    # given a string array, returns a single string of each element in the same string separated by commas and spaces
    return ', '.join(stringArray)

def setStructFields(stringArray):
    # given a string array, returns a multiline string to set struct fields given input parameters
    outputString = ""
    for str in stringArray:
        outputString = outputString + f"self.{str} = {str}\n            "
    return outputString


def main():
    """
    This is the generator code. It should take in the MF structure and generate the code
    needed to run the query. That generated code should be saved to a 
    file (e.g. _generated.py) and then run.
    """
    
    # mode = input("To test a relational algebra expression, enter input mode (terminal, file): ")

    body = f"""
    class struct:
        def __init__(self, {stringArrayToCommaString(V)}, {stringArrayToCommaString(F)}):
            {setStructFields(V)}{setStructFields(F)}
    """

    # Note: The f allows formatting with variables.
    #       Also, note the indentation is preserved.
    tmp = f"""
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    {body}
    
    return tabulate.tabulate(_global, headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    """

    # Write the generated code to a file
    open("_generated.py", "w").write(tmp)
    # Execute the generated code
    subprocess.run(["python", "_generated.py"])


if "__main__" == __name__:
    main()
